Contact Form | Feature
uzairali19/contact-form pull request #1
Opened 2021-08-31 23:52 UTC by uzairali19

This branch creates forms with HTML5 validations and parses a Figma design to create a UI. This is a test repository and is used to create an HTML form to put the form data in [Formspree](https://formspree.io/).

2021-09-01 20:07 UTC, jmontanholi requested changes
Hello Uzair! 

You have done a great job so far, but there are still some things that you can improve before going to the next project. 😄 

✅ Your project is looking amazingly similar to the template you used, congratulations on that!
✅ You don't have any linter errors!
✅ Your form is working nicely!

## Required Changes ♻️
_Check the comments under the review._

- [ ] I see that you are using Git Flow, that is nice! Unfortunately, you should consider using GitHub flow instead. This is supposed to go from a feature branch directly into the Main branch. 😄 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I working on optional suggestions is always good, with them you may learn something new or make your project look more professional._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

![](https://media0.giphy.com/media/VdW96O9QVNXkkharuG/giphy.gif)

2021-09-01 20:07 UTC, jmontanholi commented on README.md
> +![screenshot](./app_screenshot.png)
- [x] I can see that you have a README.file, which is great already. But apparently, this README is not really filled with the right information about the project. It would be very nice if you filled it with the correct information. This way you will have a professional repo with a good introduction to the project. 😄

2021-09-01 20:07 UTC, jmontanholi commented on index.html
> +      </div>
- [x] Please consider using the `<section>` instead of the non-semantic `<div>` tag where you have a different section of the page. This will make your code more readable and semantic.

2021-09-01 20:07 UTC, jmontanholi commented on index.html
> +    </div>
## [OPTIONAL]
- [x] You should consider using a `<footer>` tag instead of a `<div>`. This makes your code more semantical and professional.

2021-09-01 20:07 UTC, jmontanholi commented on index.html
> +              </div>
- [x] Instead of `<div>` you could consider using the `<fieldset>` tag for input groups inside forms. This is more semantic as well.

2021-09-01 20:07 UTC, jmontanholi commented on index.html
> +                    maxlength="50"
- [x] The name input max length should be equal to 30. You could separate it into first name and last name if you want to give the user more space. 😄

2021-09-01 20:07 UTC, jmontanholi commented on index.html
> +                  />
- [x] It would be better if **All** your inputs had the `required` attribute. This way you won't get forms missing important information!

2021-09-01 20:07 UTC, jmontanholi commented on index.html
> +                class="btn btn-light text-primary col-4 button-margin"
- [ ] Your submit button is looking great! Unfortunately, it needs to look as close as possible to the one in the template, so please consider styling the hover and the active pseudoclasses of the button to look like it. 😄 

Your button: 
![image](https://user-images.githubusercontent.com/73256642/131736236-94944791-e2a6-414e-ad41-c37c6cc62d83.png)
Template button:
![image](https://user-images.githubusercontent.com/73256642/131736362-77df8f15-9ee9-411c-b2d7-2db9d861d867.png)

2021-09-02 08:05 UTC, uzairali19 commented
> Hello Uzair!
> 
> You have done a great job so far, but there are still some things that you can improve before going to the next project. 😄
> 
> ✅ Your project is looking amazingly similar to the template you used, congratulations on that!
> ✅ You don't have any linter errors!
> ✅ Your form is working nicely!
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> * [x]  I see that you are using Git Flow, that is nice! Unfortunately, you should consider using GitHub flow instead. This is supposed to go from a feature branch directly into the Main branch. 😄
> * [x]  It is always good to have meaningful names as your branche's name, you could try something like "desktop-form" for example. 👍🏻
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I working on optional suggestions is always good, with them you may learn something new or make your project look more professional._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
> 
> ![](https://camo.githubusercontent.com/0f82381c4c9c6730ea6b6414e48d592b905e0f5c15d34fafc0c323898df84234/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f56645739364f3951564e586b6b68617275472f67697068792e676966)

Hello @jmontanholi ,

Thank you for a detailed review. I have made all the necessary changes. However, I won't be able to change the branch name as that will close the pull request and I would have to make a new request. I still think that is the way to go about my projects, So, thanks for pointing that out.

Cheers,

Uzair

2021-09-02 16:18 UTC, ZeenatLawal approved these changes
Hi @uzairali19, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

## Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-09 12:40 UTC, merged